name: final_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  quickalert: ^1.0.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  sticky_headers: ^0.3.0+2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  intl: ^0.19.0
  google_fonts: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/raw/
